### ISSUE TITLE
setuptools or numpy.distutils for the setup.py file?

### ISSUE THREAD

**Issue by dprada** [uibcdf/OpenMMGBSA#2]
We should check the differences between using setuptools and numpy.distutils to configure the setup.py file. Which one should we use?

**Comment by LMMV** [comment]
The Python Packaging User Guide (https://packaging.python.org/guides/tool-recommendations/) recommends now:

Use setuptools to define projects and create Source Distributions.

And explains:

"Although you can use pure distutils for many projects, it does not support defining dependencies on other projects and is missing several convenience utilities for automatically populating package metadata correctly that are provided by setuptools. Being outside the standard library, setuptools also offers a more consistent feature set across different versions of Python, and (unlike distutils), setuptools will be updated to produce the upcoming “Metadata 2.0” standard formats on all supported versions.

Even for projects that do choose to use distutils, when pip installs such projects directly from source (rather than installing from a prebuilt wheel file), it will actually build your project using setuptools instead."

But many packages still use distutils and those that support setuptools often mix setuptools with distutils.

**Comment by dprada** [comment]
Hmm, we should then work with both. Let's keep it this way as long as the setup.py file is functional.

**Comment by dprada** [comment]
This issue is solved if the MOLSSI cookie-cutter is used. See uibcdf/OpenPharmacophore#4

**Comment by dprada** [comment]
Duplicate of uibcdf/OpenPharmacophore#4
